// <auto-generated />
using System;
using CS665_PizzaRestaurantApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CS665_PizzaRestaurantApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250411182254_UpdatedOrderModel")]
    partial class UpdatedOrderModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("CS665_PizzaRestaurantApp.Models.CustomerModel", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerID");

                    b.ToTable("CustomerModels");
                });

            modelBuilder.Entity("CS665_PizzaRestaurantApp.Models.MenuItemModel", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemID");

                    b.ToTable("MenuItemModels");
                });

            modelBuilder.Entity("CS665_PizzaRestaurantApp.Models.OrderDetailModel", b =>
                {
                    b.Property<int>("OrderDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MenuItemModelItemID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderModelOrderID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderDetailID");

                    b.HasIndex("ItemID");

                    b.HasIndex("MenuItemModelItemID");

                    b.HasIndex("OrderID");

                    b.HasIndex("OrderModelOrderID");

                    b.ToTable("OrderDetailModels");
                });

            modelBuilder.Entity("CS665_PizzaRestaurantApp.Models.OrderModel", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerID");

                    b.ToTable("OrderModels");
                });

            modelBuilder.Entity("CS665_PizzaRestaurantApp.Models.OrderDetailModel", b =>
                {
                    b.HasOne("CS665_PizzaRestaurantApp.Models.MenuItemModel", "MenuItem")
                        .WithMany()
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CS665_PizzaRestaurantApp.Models.MenuItemModel", null)
                        .WithMany("OrderDetails")
                        .HasForeignKey("MenuItemModelItemID");

                    b.HasOne("CS665_PizzaRestaurantApp.Models.OrderModel", "Order")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CS665_PizzaRestaurantApp.Models.OrderModel", null)
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderModelOrderID");

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CS665_PizzaRestaurantApp.Models.OrderModel", b =>
                {
                    b.HasOne("CS665_PizzaRestaurantApp.Models.CustomerModel", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CS665_PizzaRestaurantApp.Models.CustomerModel", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CS665_PizzaRestaurantApp.Models.MenuItemModel", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("CS665_PizzaRestaurantApp.Models.OrderModel", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
